export const territoriesTypes = {
    GET_REGIONS: 'GET_REGIONS',

    GET_PROVINCES_BY_REGION: 'GET_PROVINCES_BY_REGION',

    GET_MUNICIPALITIES_BY_PROVINCES_BY_REGIONS: 'GET_MUNICIPALITIES_BY_PROVINCES_BY_REGIONS',
}